name: ${mod_id} # the plugins name as it should appear in the plugin list /pl
version: ${version} # the plugin's version
authors: ${authors}
main: ${group}.spigot.SpigotPlugin
api-version: ${spigot_api_compatibility} # the version of the API you want to use, required starting with 1.13
description: ${description}
website: ${homepage}
