modLoader = "javafml" #//mandatory
loaderVersion = "*" # // mandatory. Allow all forge versions as we are definding what Minecraft versions we require later on
license = "${mod_license}"
issueTrackerURL = "${issues}"


[[mods]] #//mandatory
modId = "${mod_id}" #//mandatory
version = "${version}" #//mandatory, gets the version number from jar populated by the build.gradle script
displayName = "${mod_name}" #//mandatory
authors = ["Abelpro678"] # Should be done with `$authors`, but architectury complains
#//updateJSONURL="https://change.me.example.invalid/updates.json" # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
displayURL = "${homepage}"
description = "${description}" #//mandatory. The description text for the mod
logoFile = "assets/${mod_id}/icon.png"
catalogueImageIcon = "assets/${mod_id}/icon.png"
credits = "Massive thanks to: ..."
#// if not set defaults to "false"
clientSideOnly = "false"
#// if not set side defaults to "BOTH"
#// change to "BOTH" when adding server support
side = "BOTH"
#// Allow any version to be present (or not) on the server
acceptableRemoteVersions = "*"
updateJSONURL = "${forgeUpdateJSONURL}"

[[dependencies.${ mod_id }]]
modId = "forge" #mandatory
mandatory = true  # Forge syntax
versionRange = "[0,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true  # Forge syntax
versionRange = "${compatible_forgemc_versions}" # Where we set what version of mc it is avalible for
ordering = "AFTER"
side = "BOTH"