modLoader = "javafml" #//mandatory
loaderVersion = "*" # // mandatory. Allow all forge versions as we are definding what Minecraft versions we require later on
license = "GPLv3"
issueTrackerURL = "https://github.com/Abelkrijgtalles/mojang-maps/issues"


[[mods]] #//mandatory
modId = "mojang_maps" #//mandatory
version = "${version}" #//mandatory, gets the version number from jar populated by the build.gradle script
displayName = "Mojang Maps" #//mandatory
authors = ["Abelpro678", "Contributors"]
#//updateJSONURL="https://change.me.example.invalid/updates.json" # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
displayURL = "https://github.com/Abelkrijgtalles/mojang-maps"
description = "A Google Maps like navigation system for Minecraft." #//mandatory. The description text for the mod
logoFile = "assets/mojang_maps/icon.png"
catalogueImageIcon = "assets/mojang_maps/icon.png"
# If the link changes, don't forget to update the build.gradle.kts script
credits = "See contributors, and https://github.com/Abelkrijgtalles/mojang-maps#creditscode-i-used"
#// if not set defaults to "false"
clientSideOnly = "false"
#// if not set side defaults to "BOTH"
#// change to "BOTH" when adding server support
side = "SERVER"
#// Allow any version to be present (or not) on the server
acceptableRemoteVersions = "*"
updateJSONURL = "https://api.modrinth.com/updates/mojang-maps/forge_updates.json"

[[dependencies.mojang_maps]]
modId = "forge" #mandatory
mandatory = true  # Forge syntax
versionRange = "[0,)" #mandatory
ordering = "NONE"
side = "SERVER"

[[dependencies.mojang_maps]]
modId = "minecraft"
mandatory = true  # Forge syntax
versionRange = "${compatible_minecraft_versions}" # Where we set what version of mc it is avalible for
ordering = "AFTER"
side = "SERVER"