#!/bin/sh

#
# MojangMaps
# Copyright (C) 2024 Abel van Hulst/Abelkrijgtalles/Abelpro678
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

echo "==================== Note: All build jars will be in the folder called 'buildAllJars' ===================="
mkdir -p buildAllJars | true

# Loop trough everything in the version properties folder
for d in versionProperties/*; do
  # Get the name of the version that is going to be compiled
  version=$(echo "$d" | sed "s/versionProperties\///" | sed "s/.properties//")

  # Clean out the folders, build it, and merge it
  # (We could use "./" to run gradlew, but as it is a shell script im going to be running it with the "sh" command)
  echo "==================== Cleaning workspace to build $version ===================="
  sh gradlew clean -PmcVer=$version --no-daemon || true
  echo "====================Building $version ===================="
  sh gradlew build -PmcVer=$version --no-daemon || true
  echo "==================== Merging $version ===================="
  sh gradlew mergeJars -PmcVer=$version --no-daemon || true
  echo "==================== Moving jar ===================="
  mv Merged/*.jar buildAllJars/ || true
  # The "| true" at the end of those are just to make sure the script continues even if a build fails
done
