name: MojangMaps
version: '${project.version}'
main: nl.abelkrijgtalles.mojangmaps.MojangMaps
api-version: '1.20'
authors: [ Abelpro678 ]
description: A Google Maps like navigation system for Minecraft.
website: https://github.com/Abelkrijgtalles/mojang-maps
commands:
  registerlocation:
    description: Register a location.
  calculatedistance:
    description: Calculates the distance to every point.