name: MojangMaps
version: '${project.version}'
main: nl.abelkrijgtalles.MojangMaps.MojangMaps
api-version: '1.20'
authors: [ Abelpro678 ]
description: A Google Maps like navigation system for Minecraft.
website: https://github.com/Abelkrijgtalles/mojang-maps
libraries:
  - dev.jorel:commandapi-bukkit-shade:9.3.0
  - com.samjakob:SpiGUI:1.3.1

permissions:
  mojangmaps.register:
    description: Lets you register things.
    default: op
    children:
      mojangmaps.register.location:
        description: Lets you register a location.
        default: op
      mojangmaps.register.road:
        description: Lets you register a road.
        default: op
  mojangmaps.using:
    description: Lets you use Mojang Maps.
    default: true
    children:
      mojangmaps.using.goto:
        description: Lets you go to a location.
        default: true
      mojangmaps.using.viewlocation:
        description: Lets you view your location.
        default: true
      mojangmaps.using.navigation:
        description: Lets you go to a location and view the navigation in GUI form.
        default: true
  mojangmaps.util:
    description: Some useful tools for an admin.
    default: op
    children:
      mojangmaps.util.reloadconfigs:
        description: Lets you reload your configs from disk.
        default: op