name: MojangMaps
version: '${project.version}'
main: nl.abelkrijgtalles.mojangmaps.MojangMaps
api-version: '1.20'
authors: [ 0Abel ]
description: A Google Maps like navigation system for Minecraft.
website: https://github.com/Abelkrijgtalles/mojang-maps
commands:
  registerlocation:
    description: Register a location.
  registerroad:
    description: Register a road.
  goto:
    description: Go to a specific location