package nl.abelkrijgtalles.mojangmaps.managers.config;

import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

public class NodesConfig {

    private static File file;
    private static FileConfiguration customFile;

    // Idk weird setup I guess
    public static void setup() {
        file = new File(Bukkit.getServer().getPluginManager().getPlugin("MojangMaps").getDataFolder(), "nodes.yml");

        if (!file.exists()) {
            try {
                file.createNewFile();
                // Write some things in the configuration file
                customFile = YamlConfiguration.loadConfiguration(file);
                NodesConfig.get().options().header("This is auto-generated by Mojang Maps.\nChanging anything in this file will result in a broken Mojang Maps.");
                NodesConfig.get().addDefault("locations", new ArrayList<Location>());
                NodesConfig.get().options().copyDefaults(true);
                NodesConfig.save();
            } catch (IOException e) {
                Bukkit.getLogger().warning("Could not create the configuration file nodes.yml.");
            }
        }
        customFile = YamlConfiguration.loadConfiguration(file);
    }

    public static FileConfiguration get() {
        return customFile;
    }

    public static void save() {
        try {
            customFile.save(file);
        } catch (IOException e) {
            Bukkit.getLogger().warning("Could not save the configuration file nodes.yml.");
        }
    }

    public static void reload() {
        customFile = YamlConfiguration.loadConfiguration(file);
    }

}
