/*
 * mojang-maps.platform.main
 * Copyright (C) 2025 Abel van Hulst/Abelkrijgtalles/Abelpro678
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package nl.abelkrijgtalles.mojangmaps.platform.world;

// Only the particles convertable to ParticleOptions.
// https://minecraft.wiki/w/Particles_(Java_Edition)
public enum Particle {
    ANGRY_VILLAGER,
    ASH,
    BUBBLE,
    BUBBLE_COLUMN_UP,
    BUBBLE_POP,
    CAMPFIRE_COSY_SMOKE,
    CAMPFIRE_SIGNAL_SMOKE,
    CHERRY_LEAVES,
    CLOUD,
    COMPOSTER,
    CRIMSON_SPORE,
    CRIT,
    CURRENT_DOWN,
    DAMAGE_INDICATOR,
    DOLPHIN,
    DRAGON_BREATH,
    DRIPPING_DRIPSTONE_LAVA,
    DRIPPING_DRIPSTONE_WATER,
    DRIPPING_HONEY,
    DRIPPING_LAVA,
    DRIPPING_OBSIDIAN_TEAR,
    DRIPPING_WATER,
    DUST_PLUME,
    EFFECT,
    EGG_CRACK,
    ELDER_GUARDIAN,
    ELECTRIC_SPARK,
    ENCHANT,
    ENCHANTED_HIT,
    END_ROD,
    EXPLOSION,
    EXPLOSION_EMITTER,
    FALLING_DRIPSTONE_LAVA,
    FALLING_DRIPSTONE_WATER,
    FALLING_HONEY,
    FALLING_LAVA,
    FALLING_NECTAR,
    FALLING_OBSIDIAN_TEAR,
    FALLING_SPORE_BLOSSOM,
    FALLING_WATER,
    FIREFLY,
    FIREWORK,
    FISHING,
    FLAME,
    FLASH,
    GLOW,
    GLOW_SQUID_INK,
    GUST,
    GUST_EMITTER,
    GUST_EMITTER_LARGE,
    GUST_EMITTER_SMALL,
    HAPPY_VILLAGER,
    HEART,
    INFESTED,
    INSTANT_EFFECT,
    ITEM_COBWEB,
    ITEM_SLIME,
    ITEM_SNOWBALL,
    LANDING_HONEY,
    LANDING_LAVA,
    LANDING_OBSIDIAN_TEAR,
    LARGE_SMOKE,
    LAVA,
    MYCELIUM,
    NAUTILUS,
    NOTE,
    OMINOUS_SPAWNING,
    PALE_OAK_LEAVES,
    POOF,
    PORTAL,
    RAID_OMEN,
    RAIN,
    REVERSE_PORTAL,
    SCRAPE,
    SCULK_CHARGE_POP,
    SCULK_SOUL,
    SMALL_FLAME,
    SMALL_GUST,
    SMOKE,
    SNEEZE,
    SNOWFLAKE,
    SONIC_BOOM,
    SOUL,
    SOUL_FIRE_FLAME,
    SPIT,
    SPLASH,
    SPORE_BLOSSOM_AIR,
    SQUID_INK,
    SWEEP_ATTACK,
    TOTEM_OF_UNDYING,
    TRIAL_OMEN,
    TRIAL_SPAWNER_DETECTION,
    TRIAL_SPAWNER_DETECTION_OMINOUS,
    UNDERWATER,
    VAULT_CONNECTION,
    WARPED_SPORE,
    WAX_OFF,
    WAX_ON,
    WHITE_ASH,
    WHITE_SMOKE,
    WITCH
}
